[package]
name = "rebased_pixels"
version = "0.1.0"
edition = "2024.beta"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", rev = "testnet", subdir = "crates/iota-framework/packages/iota-framework" }
MoveStdlib = { git = "https://github.com/iotaledger/iota.git", rev = "testnet", subdir = "crates/iota-framework/packages/move-stdlib" }

[addresses]
nft_admin = "0x0"
iota = "0x2"

[dev-addresses]
nft_admin = "0x0"
iota = "0x2"

[dev-dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", rev = "testnet", subdir = "crates/iota-framework/packages/iota-framework" }
MoveStdlib = { git = "https://github.com/iotaledger/iota.git", rev = "testnet", subdir = "crates/iota-framework/packages/move-stdlib" } 